spring.application.name=QuizExam_Student
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/db_test
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.expiration=604800000
jwt.secret="secret"
uploads.subject = ./uploads/img-subject
uploads.question = ./uploads/img-question
spring.web.resources.static-locations=classpath:/static/, file:./uploads/
spring.mvc.static-path-pattern=/uploads/**

# Disable Hibernate SQL noise
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# Enable Spring Security & Web Debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=DEBUG
