services:
    app:
        build: .
        container_name: quiz-exam-backend
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_test
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=12345678
        volumes:
            - ./uploads:/app/uploads
            - ./target/classes:/app/target/classes
        depends_on:
            db:
                condition: service_healthy
        networks:
            - dev_network

    db:
        image: mysql:8.0
        container_name: quiz-exam-db
        environment:
            - MYSQL_DATABASE=db_test
            - MYSQL_ROOT_PASSWORD=12345678
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
        networks:
            - dev_network

    quiz-nginx:
        image: nginx:latest
        container_name: quiz-nginx
        ports:
        - "8081:80"
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        extra_hosts:
        - "host.docker.internal:host-gateway"
        restart: always
        networks:
            - dev_network

volumes:
    mysql_data:

networks:
    dev_network:
        name: dev_network
        driver: bridge
        external: true
